name: Capture State Data

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'pelbot/config'


env:
  CAPTURE_RANGE: all
  CAPTURE_TYPE: historical
  STATE: LA
  ORG_NAME: openelections
  DATA_REPO_NAME: openelections-data-la

jobs:
  setup-and-run-bot:
    name: Setup and Run PelicanBot
    runs-on: ubuntu-latest
    outputs:
      data-changed: ${{ steps.verify-changed-files.outputs.files_changed }}
    steps:
      - name: Checkout Local Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -
        working-directory: pelbot

      - name: Run PelicanBot
        run: |
          poetry install
          poetry run python -m run
        working-directory: pelbot
        env:
          CAPTURE_RANGE: ${{ env.CAPTURE_RANGE }}
          CAPTURE_TYPE: ${{ env.CAPTURE_TYPE }}
          STATE: ${{ env.STATE }}

      - name: Verify Changed files
        id: verify-changed-files
        uses: tj-actions/verify-changed-files@v16
        with:
          files: |
            data/**


      - name: Commit and Push Changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated Raw Election Files
          branch: main
          file_pattern: data/**/*
        env:
          GIT_USER_NAME: ${{ secrets.USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.USER_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-data-repo:
    name: Notify Data Repo
    needs: setup-and-run-bot
    runs-on: ubuntu-latest
    if: needs.setup-and-run-bot.result == 'success'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ env.ORG_NAME }}/${{ env.DATA_REPO_NAME }}
          event-type: import-data-trigger
