name: Capture State Data

on:
  schedule:
    # Runs at 1 AM every day
  - cron: '0 1 * * *'

  workflow_dispatch:


env:
  CAPTURE_RANGE: 2023
  CAPTURE_TYPE: historical
  STATE: LA
  ORG_NAME: openelections
  DATA_REPO_NAME: openelections-data-la


jobs:
  get-results:
    name: Get Election Data
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
    - name: Checkout Local Repo
      uses: actions/checkout@v4

      # Setup proper Python Version
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

      # Intall Poetry
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python -
      working-directory: pelbot

    - name: Install Deps and run PelicanBot
      run: |
        poetry install
        poetry run python -m run
      working-directory: pelbot
      env:
        CAPTURE_RANGE: ${{ env.CAPTURE_RANGE }}
        CAPTURE_TYPE: ${{ env.CAPTURE_TYPE }}
        STATE: ${{ env.STATE }}

    # TODO: Setup ElectionBot & Import GPG Key for Verified Commits
    # Docs: https://github.com/crazy-max/ghaction-import-gpg?tab=readme-ov-file#usage

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Updated Raw Election Files
        branch: main
        file_pattern: data/**/*  # Where are we looking for changes?
        repository: .       # Working within the root of your repository
        commit_user_name: ${{ secrets.USER_NAME }}
        commit_user_email: ${{ secrets.USER_EMAIL }}
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Need to use custom token to trigger data sync notification


  notify-data-repo:
    name: Notify Data Repo
    needs: get-results
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: ${{ env.ORG_NAME }}/${{ env.DATA_REPO_NAME }}
        event-type: import-data-trigger
